apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget-ingress
  namespace: budget-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: budget.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: budget-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: budget-ui
                port:
                  number: 80
