apiVersion: v1
kind: Service
metadata:
  name: budget-ui
  namespace: budget-app
spec:
  selector:
    app: budget-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
